spring.application.name=backend

spring.data.mongodb.authentication-database=admin
spring.data.mongodb.database=DeteccionEstrabismo
spring.data.mongodb.uri=mongodb+srv://ValentinaNeira:hItpzR6iPYmWlyFu@deteccionestrabismo.php1cox.mongodb.net/DeteccionEstrabismo?retryWrites=true&w=majority

# JWT Configuration
jwt.secret=eYzz8p7tCbdxvrqk4jPf+3nknoe8ZFWXZccWpFRgBkqYA5AVglCKFlwOO1Kbcf6TpzHyOdeosV1k0DonoA7ifg==
jwt.expiration=3600000
#Correo Electronico
#El servidor SMTP que usaremos. En este caso el de Gmail.
spring.mail.host=smtp.gmail.com
#El puerto que usa SMTP con SSL (seguridad).
spring.mail.port=465
#El Correo que envie los mensajes
spring.mail.username=deteccionestrabismo@gmail.com
#Generamos una Contrase�a para apps externas con google
spring.mail.password=gibrmmiynqjqvelb
#obliga a que el servidor SMTP pida usuario y contrase�a.
spring.mail.properties.mail.smtp.auth=true
#Obliga a usar TLS (Transport Layer Security). Esto asegura que el correo viaje cifrado y no en texto plano.
spring.mail.properties.mail.smtp.ssl.enable=true

logging.level.org.springframework.mail=DEBUG

# CORS Configuration
spring.mvc.cors.allowed-origins=http://192.168.0.3:8080
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.mvc.cors.allowed-headers=*
spring.mvc.cors.allow-credentials=true
